"""empty message

Revision ID: 18e7f5e9abaa
Revises: 685cdb7015ff
Create Date: 2018-06-05 21:36:33.251924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e7f5e9abaa'
down_revision = '685cdb7015ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'art', type_='foreignkey')
    op.create_foreign_key(None, 'art', 'person', ['user_id'], ['id'])
    op.add_column('playlist', sa.Column('desc', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlist', 'desc')
    op.drop_constraint(None, 'art', type_='foreignkey')
    op.create_foreign_key(None, 'art', 'artist', ['user_id'], ['id'])
    # ### end Alembic commands ###
