"""empty message

Revision ID: 9e40fbc120fa
Revises: 6bf5f9183a0f
Create Date: 2018-06-05 10:20:16.365813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e40fbc120fa'
down_revision = '6bf5f9183a0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playlist_art',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('art_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['art_id'], ['art.id'], ),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.PrimaryKeyConstraint('playlist_id', 'art_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_art')
    op.drop_table('playlist')
    # ### end Alembic commands ###
