"""empty message

Revision ID: acec163cf922
Revises: 7852024b30c4
Create Date: 2018-06-01 15:00:36.293909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acec163cf922'
down_revision = '7852024b30c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('bio', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'bio')
    # ### end Alembic commands ###
