"""empty message

Revision ID: d6d2e54f734d
Revises: 9e40fbc120fa
Create Date: 2018-06-05 18:50:19.355836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d2e54f734d'
down_revision = '9e40fbc120fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('art', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'art', 'artist', ['user_id'], ['id'])
    op.drop_constraint(None, 'artist', type_='foreignkey')
    op.drop_column('artist', 'account_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('account_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'artist', 'person', ['account_id'], ['id'])
    op.drop_constraint(None, 'art', type_='foreignkey')
    op.drop_column('art', 'user_id')
    # ### end Alembic commands ###
